version: 0.2

env:
  variables:
    PLATFORM: "linux/arm64/v8"
    AWS_ACCOUNT_ID: "265165126141"
    AWS_REGION: "us-east-1"

phases:
  # install:
  #   commands:
  #     - echo Entered the install phase...
  #     - apt-get update -y
  #     - apt-get install -y maven
  #   finally:
  #     - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Logging Docker into ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - docker build ./.devcontainer/Dockerfile
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

reports:
  arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
    files:
      - "**/*"
    base-directory: 'target/tests/reports'
    discard-paths: no
  reportGroupCucumberJson:
    files:
      - 'cucumber/target/cucumber-tests.xml'
    discard-paths: yes
    file-format: CUCUMBERJSON # default is JUNITXML
artifacts:
  files:
    - target/messageUtil-1.0.jar
  discard-paths: yes
  secondary-artifacts:
    artifact1:
      files:
        - target/artifact-1.0.jar
      discard-paths: yes
    artifact2:
      files:
        - target/artifact-2.0.jar
      discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
